language: csharp
solution: solution-name.sln
install:
  - nuget restore BuzzCrawler.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BuzzCrawler.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./tests/BuzzCrawler.Tests/bin/Release/BuzzCrawler.Tests.dll
