language: csharp
solution: solution-name.sln
install:
  - nuget restore BuzzCrawler.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BuzzCrawler.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./BuzzCrawler.Tests/bin/Release/BuzzCrawler.Tests.dll
